# Copyright © 2025 Charles Choi
#
#+OPTIONS: toc:nil num:0 html-postamble:nil html-preamble:nil
#+HTML_HEAD: <meta name="keywords" content="installation"/>
#+HTML_HEAD: <meta name="description" content="Scrim Installation"/>
#+HTML_HEAD: <meta name="robots" content="index, anchors"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style1.css" />

#+HTML: <a name="Installation"></a>
* Installation

** Emacs Server Setup

For *Scrim* to work, the following must be setup on the Emacs side:

1. Emacs must be setup to run as a [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Emacs-Server.html][server]]. This enables other external programs to call on Emacs to edit text or run a command.
2. The Emacs /server/ must be setup to use a TCP socket for communication.
3. The library ~org-protocol~ must be loaded.

The following Elisp can accomplish the above. Some variant of this code should exist in your Emacs initialization file.

#+begin_src elisp :lexical no
  (setopt server-use-tcp t)               ; enable TCP socket communication
  (server-start)                          ; starts Emacs server
  (require 'org-protocol)                 ; loads Org Protocol library
#+end_src

You should be able to test if the ~server~ is running by inspecting if the following file exists when Emacs is running:

~<user-emacs-directory>/server/server~

Note that ~<user-emacs-directory>~ is your initialization directory. This is typically ~$HOME/.emacs.d~ but can also be ~$HOME/.config/emacs~.

For example if your initialization directory is ~$HOME/.emacs.d~, you can test for this file's existence from the terminal (command line) using the following ~ls~ invocation:

#+begin_example
  $ ls ~/.emacs.d/server/server
#+end_example

The contents of the file named ~server~ is a shared secret that is generated by Emacs /server/. We will refer to ~server~ as the shared secret file.

Note that *Scrim* is designed to use the default settings for Emacs /server/ with regards to file and directory locations.


** Scrim Shared Secret File Permission

By default, files outside of an macOS app's sandbox are not accessible (read, write) without user permission. To gain permission, the user must manually select that file via a macOS file browser. 

The shared secret file ~server~ is outside of the sandbox for *Scrim*. As such, the user must manually select it.

From the status bar menu for *Scrim*, select the menu item "Setup". A window will be displayed with instructions on how to select the shared secret file.

Note that this file selection should be a “one-time” operation only as *Scrim* will remember it until it is reset or *Scrim* is deleted from the system.


* References
- [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Emacs-Server.html][Emacs Server (GNU Emacs Manual)]]
- [[https://www.gnu.org/software/emacs/manual/html_node/emacs/TCP-Emacs-server.html][TCP Emacs server (GNU Emacs Manual)]]
- [[https://en.wikipedia.org/wiki/Unix_domain_socket][Unix domain socket - Wikipedia]]
  

  
